apiVersion: auth.vault.crossplane.io/v1alpha1
kind: Jwt
metadata:
  name: test0
spec:
  forProvider:
    backend: jwt
    role_type: jwt
    bound_audiences: ["test"]
    user_claim: user_email
  providerConfigRef:
    name: provider-vault
