apiVersion: aws.vault.crossplane.io/v1alpha1
kind: Role
metadata:
  name: testrole2
spec:
  forProvider:
    authBackend: aws
    credentialType: assumed_role
    iamRolesArn:
      - arn:aws:iam::797740695898:role/brenno-role-test2
  providerConfigRef:
    name: provider-vault