apiVersion: aws.vault.crossplane.io/v1alpha1
kind: Role
metadata:
  name: testrole2
spec:
  forProvider:
    authBackend: aws
    credentialType: assumed_role
    policyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "ec2:*",
            "Resource": "*"
          }
        ]
      }
  providerConfigRef:
    name: provider-vault