apiVersion: aws.vault.crossplane.io/v1alpha1
kind: Role
metadata:
  name: testrole1
spec:
  forProvider:
    authBackend: aws
    credentialType: assumed_role
    iamRolesArn:
      - arn:aws:iam::123456789012:role/vault-provider-role
      - arn:aws:iam::123456789012:role/vault-provider-iam
  providerConfigRef:
    name: provider-vault