apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: provider-vault
type: Opaque
data:
  credentials: aHZzLmtRb25CUHJXVFEySW1SOWc0a0pvMDB4TA==
---
apiVersion: vault.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-vault
spec:
  timeout: 10_000_000_000
  address: http://localhost:8200
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-vault
      key: credentials
